homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  customize: !include_dir_merge_named customize

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  cors_allowed_origins:
    - http://localhost:3000

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Logs
logger:
  default: info

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
light: !include_dir_merge_list light
climate: !include_dir_merge_list climate
group: !include_dir_merge_named group
automation: !include_dir_merge_list automation
script: !include_dir_named script
camera: !include_dir_merge_list camera
media_player: !include_dir_merge_list media_player
input_boolean: !include_dir_merge_named input_booleans

# Zwave
zwave:
  usb_path: /dev/zwave

# RFXCOM
rfxtrx:
  device: /dev/rfxcom



device_tracker:
  - platform: unifi
    host: 192.168.39.2
    consider_home: 180
    track_new_devices: false
    username: ashwin
    password: !secret unifi_password


#device_sun_light_trigger:

notify:
  - name: notify
    platform: pushbullet
    api_key: !secret pushbullet_api_key
