- alias: Badkamerverlichting
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_17_10
    to: '8'
  condition:
    - condition: time
      after: '23:00'
      before: '06:30'
  action:
    service: homeassistant.turn_on
    entity_id: script.badkamer_timed_night
