- alias: WC verlichting ('s Nachts')
  hide_entity: True
  trigger:
    platform: state
    entity_id: switch.wc_boven
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.wc_boven
        state: 'off'
      - condition: time
        after: '23:00'
        before: '06:30'
  action:
    service: homeassistant.turn_on
    entity_id: script.wc_boven_timed_night
