- alias: Slaapkamer
  hide_entity: True
  trigger:
    platform: state
    entity_id: climate.slaapkamer
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: group.climate_slaapkamer
        temperature: '{{states.climate.slaapkamer.attributes.temperature}}'