- alias: Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.pushbullet
    data:
      title: "Home Assistant update beschikbaar"
      message: "Home Assistant {% raw %} {{ states.updater.updater.state }} {% endraw %} is beschikbaar."
